Bookmarker/urls.py
import debug_toolbar
from accounts.views import dashboard
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetCompleteView

urlpatterns = [
    path('', dashboard, name='home'),
    path('accounts/', include('accounts.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),

    # path('custom-login/', login_view, name='custom-login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('__debug__/', include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import create_image, image_detail, image_like, list_images, image_ranking

app_name = 'images'

urlpatterns = [
    path('', list_images, name='image-list'),
    path('most-viewed/', image_ranking, name='image-ranking'),
    path('create-image/', create_image, name='create-image'),
    path('image-detail/<slug:slug>/', image_detail, name='image-detail'),
    path('like/', image_like, name='like'),
]

images/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings
from django.utils.text import slugify

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    url = models.URLField()
    image = models.ImageField(upload_to='%Y/%m/%d')
    description = models.TextField()
    slug = models.SlugField(unique=True, max_length=250)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    users_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    def __str_(self):
        return self.title

    def get_absolute_url(self):
        return reverse('images:image-detail', args=[self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

images/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Image
from django.utils.text import slugify
from django.core.files.base import ContentFile
from urllib import request


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput
        }

    
    def clean_url(self):
        url = self.cleaned_data.get('url')
        valid_extensions = ['jpeg', 'jpg']
        extension = url.rsplit('.', 1)[1].lower()
        if not extension in valid_extensions:
            raise forms.ValidationError('Invalid Extension')
        return url


    def save(self, force_insert=False, force_update=False, commit=True):
        
        # create a new image instance
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        # Generate a new image name by using a name and the image extension
        image_name = f"{name}.{extension}"

        # Download the image from the given url
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()
        return image

images/views.py
from re import template
from django.contrib.auth import login
from django.db.models import Count
from actions.utils import create_action
from django.forms.widgets import PasswordInput
from images.models import Image
from django.http import JsonResponse, HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .forms import ImageCreateForm
from django.contrib import messages
from comon.decorators import ajax_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings
import redis

# Connect to redis
r = redis.Redis(host=settings.REDIS_HOST,
                port=settings.REDIS_PORT,
                db=settings.REDIS_DB)

@login_required
def create_image(request):
    user = request.user
    if request.method == 'POST':
        # form was submitted
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            print("form was valid")
            cd = form.cleaned_data
            new_item = form.save(commit=False)

            new_item.user = user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Successfuly added an image')
            return redirect(new_item.get_absolute_url())
        else:
            print('FORM WAS NOT VALID')
            print(form.errors)
    else:
        form = ImageCreateForm(data=request.GET)

    template_name = 'create-image.html'
    context = {
        'user': user,
        'form': form
    }

    return render(request, template_name, context)


@login_required
def image_detail(request, slug):
    image = get_object_or_404(Image, slug=slug)
    # increment the image views by 1
    total_views = r.incr(f'image:{image.id}:views')
    # increment the ranking by 1
    r.zincrby('image_ranking', 1, image.id)
    template_name = 'image-detail.html'
    
    context = {
        'image': image,
        'total_views': total_views,
    }
    print(image.title)
    return render(request, template_name, context)


@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        print('got that')
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                print('liked')
                image.users_likes.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                print('unliked')
                image.users_likes.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass

    return JsonResponse({'status':'error'})

@login_required
def list_images(request):
    print('this is the request', request.GET)
    images = Image.objects.order_by('-total_likes')
    paginator = Paginator(images, 6)
    page = request.GET.get('page')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # page is not an interger deliver the first page
        print('This page is not an interger')
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            # if the request is ajax and the page is out of range
            # return an empty page
            return HttpResponse('')
        #  if page is out of range deliver the last page of therresults
        images = paginator.page(paginator.num_pages)
    if request.is_ajax():
        context = {
            'section': 'images',
            'images': images
        }
        template_name = 'list-ajax.html'
        return render(request, template_name, context)
    
    template_name = 'list.html'
    context = {
        'images': images,
    }

    return render(request, template_name, context)

@login_required
def image_ranking(request):
    # Get image ranking dictionary
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]

    # Get the most viewed Images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))

    # most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    print(most_viewed)
    template_name = 'ranking.html'
    context = {
        'most_viewed': most_viewed
    }

    print(context['most_viewed'])
    
    return render(request, template_name, context)
    

images/templates/create-image.html
{% extends "base.html" %}

{% block title %}{% endblock title %}

{% block content %}

<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form action="." method='post'>
    {% csrf_token %}
    {{form}}
    <input type="submit">
    
</form>

{% endblock content %}

images/templates/image-detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Image Detail ({{image.title}}){% endblock title %}


{% block content %}
    <h2>{{image.title}}</h2>
    <hr>
    <div class="row">
        <div class="col-md-6 col-lg-6">
            <a href="{{image.image.url}}">
                <img src="{% thumbnail image.image 300x0%}" alt="">
            </a>
        </div>
        <div class="col-md-6 col-lg-6">
        {% with total_likes=image.users_likes.count users_like=image.users_likes.all%}
            <div class="image-info">
                <div>
                    <span class="count btn btn-outline-secondary">
                        <span class="total">{{total_likes}}</span>
                        Like{{total_likes|pluralize}}
                    </span>
                    <a href="#" data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                        {% if request.user not in users_like %}
                            <button class="btn btn-info">Like</button>
                        {% else %}
                            <button class="btn btn-warning">Unlike</button>
                        {% endif %}
                    </a>
                    <span class="count btn btn-outline-secondary">
                        <span class="total">{{total_views}}</span>
                        View{{total_views|pluralize}}
                    </span> 
                </div>
                {{image.description|linebreaks}}
            </div>
            <div class="image-like">
            {% for user in users_like %}
                <div>
                    <div class="user-profile">
                    {% comment %} <img src="{{user.profile.photo.url}}" alt=""> {% endcomment %}
                    </div>
                    <p>{{user.first_name}}</p>
                </div>
            {% empty %}
                Nobody likes this image yet
            {% endfor %}
            </div>
        {% endwith %}
        </div>
    </div>
{% endblock content %}


{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url 'images:like' %}',
        {
            id: $(this).data('id'),
            action: $(this).data('action')
        },
   
        function(data){
            var status = data['status']
            if(status == 'ok'){
                // get the previous value of the action
                var previous_value = $('a.like').data('action')
                console.log(previous_value)
                console.log($('a.like').text())

                // Toggle the action
                $('a.like').data('action', previous_value == 'like' ? 'unlike' : 'like')

                // Toggle the btn

                $('a.like').text(previous_value == 'like' ? 'Unlike' : 'Like')

                // update the number of likes
                var previous_likes = parseInt($('span.count .total').text())
                
                $('span.count .total').text(previous_value == 'like' ? previous_likes + 1 : previous_likes - 1)
                console.log(previous_likes)
            }
        }
        )

    })
{% endblock domready %}

images/templates/list-ajax.html
{% load thumbnail %}


<div class="row mt-5 mb-5" >
{% for image in images %}
    
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <a href="{{image.get_absolute_url}}"><img class="card-img-top" src="{{image.image.url}}" alt=""></a>
            <div class="card-body">
                <h5>{{image.slug}}</h5>
                <p class="card-text">{{image.description|truncatewords:10}}</p>
            </div>
        </div>
    </div>
{% endfor %}
    </div> 

images/templates/list.html
{% extends "base.html" %}

{% block content %}
<div id="image-list">
    {% include 'list-ajax.html' %}
</div>
{% endblock content %}


{% block domready %}
    var page = 1;
    var empty_page = false
    var block_request = false


    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        console.log($(window).scrollTop())
        console.log(margin)
        console.log('empty page', empty_page)
        console.log('bloack request', block_request)
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '') {
                    empty_page = true;
                    console.log('this is yet another data', data)
                }
                else {
                    block_request = false;
                    $('#image-list').append(data)
                    console.log('this is the data', data)
                }
            })
        }
    })

{% endblock domready %}

images/templates/ranking.html
{% extends "base.html" %}

{% block content %}
<h1>Images Ranking</h1>
<hr>
<div class="row">
  {% for image in most_viewed %}
    
    <div class="col-md-4">
        <div class="card" style="width: 18rem;">
            <a href="{{image.get_absolute_url}}"><img class="card-img-top" src="{{image.image.url}}" alt=""></a>
            <div class="card-body">
                <h5>{{image.slug}}</h5>
                <p class="card-text">{{image.description|truncatewords:10}}</p>
            </div>
        </div>
    </div>
{% endfor %}
   </div>
{% endblock content %}