Bookmarker/urls.py
import debug_toolbar
from accounts.views import dashboard
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetCompleteView

urlpatterns = [
    path('', dashboard, name='home'),
    path('accounts/', include('accounts.urls')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),

    # path('custom-login/', login_view, name='custom-login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('__debug__/', include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from .views import create_image, image_detail, image_like, list_images, image_ranking

app_name = 'images'

urlpatterns = [
    path('', list_images, name='image-list'),
    path('most-viewed/', image_ranking, name='image-ranking'),
    path('create-image/', create_image, name='create-image'),
    path('image-detail/<slug:slug>/', image_detail, name='image-detail'),
    path('like/', image_like, name='like'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My SocailApp{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bookmarklet.css' %}">
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse navbar-right" id="navbarNav" >
    <ul class="navbar-nav">
      <li class="nav-item {% if request.path == '/'%}
            active
          {% endif %}">
        <a class="nav-link" href="#">My Dashboard <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item {% if request.path == '/images/'%}
            active
          {% endif %}">
        <a class="nav-link" href="{% url 'images:image-list' %}">Images</a>
      </li>

      <li class="nav-item {% if request.path == '/people/'%}
            active
          {% endif %}">
        <a class="nav-link" href="{% url 'profile_list' %}">People</a>
      </li>

      {% if request.user.is_authenticated %}
          <li class="nav-item">
            <p class="nav-link">Loggedin as {{request.user.username}}</p>
          </li>
          <li class="nav-item {% if request.path == '/logout/'%}
            active
          {% endif %}">
            <a class="nav-link" href="{% url 'logout' %}">Lougout</a>
          </li>

      {% else %}
          <li class="nav-item {% if request.path == '/login/'%}
            active
          {% endif %}">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>

          <li class="nav-item {% if request.path == '/register/'%}
            active
          {% endif %}">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
      {% endif %} 

      {% comment %} <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> {% endcomment %}
    </ul>
  </div>
</nav>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} mt-2 alert-dismissible" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">X</span>
      </button>
    </div>
  {% endfor %}
{% endif %}
    
<div class="container">
{% block content %}{% endblock content %}
</div>

<div class="footer" style="margin-bottom: 0px">
<h3 class="bg-dark">This is the footer section</h3>
</div>

{% comment %} <script src="{% static 'js/bootstrap.js' %}"></script> {% endcomment %}
<script src="{% static 'js/jquery2.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>

<script>
  var csrftoken = Cookies.get('csrftoken')
  console.log(csrftoken)
  function csrfSafeMethod(method) {
    // These HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
      if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
        xhr.setRequestHeader("X-CSRFToken", csrftoken)
      }
    }
  })
  $(document).ready(function() {
    {% block domready %}
      console.log($(document))
    {% endblock domready %}
  })
</script> 


</body>
</html>